### ISSUE TITLE
Pandas Error

### ISSUE THREAD

**Issue by eliwilner** [deezer/spleeter#279]
Hi,

I'm trying to follow the examples shown on the README file with:

`
spleeter separate -i myfile.wav -p spleeter:2stems -o output

but keep getting and error msg:

`
from pandas.core.indexers import check_array_indexer
ImportError: cannot import name 'check_array_indexer' from 'pandas.core.indexers' (/home/eli/anaconda3/lib/python3.7/site-packages/pandas/core/indexers.py)
`
`
Any idea why this is happening?

**Comment by mmoussallam** [comment]
Hi @eliwilner 

Please use the "bug" issue template for this kind of problems instead of the "question" one. We need more info on your setup in order to help you.

**Comment by LaoTsing** [comment]
at me also get error:
```
Workstation:~/prediction$ python3.8 demo.py
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import pandas as pd
  File "/home/monster/.local/lib/python3.8/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/monster/.local/lib/python3.8/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/monster/.local/lib/python3.8/site-packages/pandas/core/arrays/__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "/home/monster/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "/home/monster/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "/home/monster/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/array.py", line 46, in <module>
    from pandas.core.indexers import check_array_indexer
ImportError: cannot import name 'check_array_indexer' from 'pandas.core.indexers' (/home/monster/.local/lib/python3.8/site-packages/pandas/core/indexers.py)
```

**Comment by VivianCheng228** [comment]
Same problem

**Comment by sarthak405** [comment]
Facing same problem.

**Comment by DB2799** [comment]
anyone fix this - i have the same issue and i'm new to python

**Comment by duhaime** [comment]
I fixed this with:
```
pip install pandas==1.0.1
```

**Comment by ugursoysal** [comment]
```
from pandas.core.indexers import check_array_indexer
ImportError: cannot import name 'check_array_indexer' from 'pandas.core.indexers' (/usr/local/lib/python3.7/site-packages/pandas/core/indexers.py)
```

I've tried with panda version 1.0.1 and 1.0.3, still getting the same error in Heroku environment.

**Comment by qrzhang** [comment]
I fixed this with:
```
conda update pandas
```

**Comment by LaoTsing** [comment]
> I fixed this with:
> 
> ```
> conda update pandas
> ```

Oh thank you!!!

**Comment by ganapathymanian** [comment]
> I fixed this with:
> 
> ```
> pip install pandas==1.0.1
> ```

Thanks, it worked with pandas==1.0.1

**Comment by wenchengxucool** [comment]
pip install pandas==1.3.2 --user

**Comment by LatifB** [comment]
> I fixed this with:
> 
> ```
> conda update pandas
> ```

This didn't work for me. Instead, I deactivated the anaconda environment and updated using pip. And somehow it fixed for me.
